// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: board.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO "board" (name, owner_id) VALUES ($1, $2) RETURNING id, name, owner_id, elements, created_at, updated_at
`

type CreateBoardParams struct {
	Name    string `db:"name" json:"name"`
	OwnerID string `db:"owner_id" json:"ownerId"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.OwnerID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Elements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM "board" WHERE id = $1 AND owner_id = $2
`

type DeleteBoardParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	OwnerID string    `db:"owner_id" json:"ownerId"`
}

func (q *Queries) DeleteBoard(ctx context.Context, arg DeleteBoardParams) error {
	_, err := q.db.Exec(ctx, deleteBoard, arg.ID, arg.OwnerID)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, name, owner_id, elements, created_at, updated_at FROM "board" WHERE id = $1 AND owner_id = $2
`

type GetBoardByIDParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	OwnerID string    `db:"owner_id" json:"ownerId"`
}

func (q *Queries) GetBoardByID(ctx context.Context, arg GetBoardByIDParams) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByID, arg.ID, arg.OwnerID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Elements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE "board" SET name = $2, elements = $3 WHERE id = $1 AND owner_id = $4 RETURNING id, name, owner_id, elements, created_at, updated_at
`

type UpdateBoardParams struct {
	ID       uuid.UUID       `db:"id" json:"id"`
	Name     string          `db:"name" json:"name"`
	Elements json.RawMessage `db:"elements" json:"elements"`
	OwnerID  string          `db:"owner_id" json:"ownerId"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.Name,
		arg.Elements,
		arg.OwnerID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Elements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
