// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: speech.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeechService_StreamTranscribe_FullMethodName = "/speech.SpeechService/StreamTranscribe"
	SpeechService_CleanupSession_FullMethodName   = "/speech.SpeechService/CleanupSession"
)

// SpeechServiceClient is the client API for SpeechService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeechServiceClient interface {
	StreamTranscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TranscribeRequest, TranscribeResponse], error)
	CleanupSession(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error)
}

type speechServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechServiceClient(cc grpc.ClientConnInterface) SpeechServiceClient {
	return &speechServiceClient{cc}
}

func (c *speechServiceClient) StreamTranscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TranscribeRequest, TranscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpeechService_ServiceDesc.Streams[0], SpeechService_StreamTranscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscribeRequest, TranscribeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeechService_StreamTranscribeClient = grpc.ClientStreamingClient[TranscribeRequest, TranscribeResponse]

func (c *speechServiceClient) CleanupSession(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupResponse)
	err := c.cc.Invoke(ctx, SpeechService_CleanupSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeechServiceServer is the server API for SpeechService service.
// All implementations must embed UnimplementedSpeechServiceServer
// for forward compatibility.
type SpeechServiceServer interface {
	StreamTranscribe(grpc.ClientStreamingServer[TranscribeRequest, TranscribeResponse]) error
	CleanupSession(context.Context, *CleanupRequest) (*CleanupResponse, error)
	mustEmbedUnimplementedSpeechServiceServer()
}

// UnimplementedSpeechServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeechServiceServer struct{}

func (UnimplementedSpeechServiceServer) StreamTranscribe(grpc.ClientStreamingServer[TranscribeRequest, TranscribeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTranscribe not implemented")
}
func (UnimplementedSpeechServiceServer) CleanupSession(context.Context, *CleanupRequest) (*CleanupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanupSession not implemented")
}
func (UnimplementedSpeechServiceServer) mustEmbedUnimplementedSpeechServiceServer() {}
func (UnimplementedSpeechServiceServer) testEmbeddedByValue()                       {}

// UnsafeSpeechServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechServiceServer will
// result in compilation errors.
type UnsafeSpeechServiceServer interface {
	mustEmbedUnimplementedSpeechServiceServer()
}

func RegisterSpeechServiceServer(s grpc.ServiceRegistrar, srv SpeechServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpeechServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeechService_ServiceDesc, srv)
}

func _SpeechService_StreamTranscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpeechServiceServer).StreamTranscribe(&grpc.GenericServerStream[TranscribeRequest, TranscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeechService_StreamTranscribeServer = grpc.ClientStreamingServer[TranscribeRequest, TranscribeResponse]

func _SpeechService_CleanupSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechServiceServer).CleanupSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeechService_CleanupSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechServiceServer).CleanupSession(ctx, req.(*CleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeechService_ServiceDesc is the grpc.ServiceDesc for SpeechService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.SpeechService",
	HandlerType: (*SpeechServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CleanupSession",
			Handler:    _SpeechService_CleanupSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTranscribe",
			Handler:       _SpeechService_StreamTranscribe_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "speech.proto",
}
